# Generated by Django 4.2.17 on 2025-01-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockindexwatchlist",
            options={
                "verbose_name": "StockIndex Watchlist",
                "verbose_name_plural": "StockIndex Watchlists",
            },
        ),
    ]
