# Generated by Django 4.2.17 on 2025-01-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_stockindexwatchlist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockindexwatchlist",
            name="type",
            field=models.CharField(
                default="INDEX", max_length=255, verbose_name="Type"
            ),
        ),
    ]
