# Generated by Django 4.2.17 on 2025-01-01 06:32

import apps.account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True, validators=[apps.account.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
