# Generated by Django 4.2.17 on 2025-01-01 06:35

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.account.models.avatar_upload_to, verbose_name='Avatar'),
        ),
    ]
