# Generated by Django 4.2.17 on 2025-01-01 06:43

import apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.managers.UserManager()),
            ],
        ),
    ]
