# List of top indices
TOP_INDICES = [
    "^NSEI",
    "^NSEBANK",
    "^BSESN",
    "BSE-BANK.BO",
    "NIFTY_FIN_SERVICE.NS",
]

# Set the required fields
REQUIRED_FIELDS = [
    "symbol",
    "shortName",
    "longName",
    "lastPrice",
    "previousClose",
    "open",
    "dayLow",
    "dayHigh",
]

# Stock exchange categories
NSE_CATEGORIES = [
    ("broad-market", "Broad Market Indices"),
    ("sectoral", "Sectoral Indices"),
    ("strategy", "Strategy Indices"),
    ("thematic", "Thematic Indices"),
]
BSE_CATEGORIES = [
    ("broad-market", "Broad Market Indices"),
    ("sector", "Sector Indices"),
    ("thematic", "Thematic Indices"),
    ("strategy", "Strategy Indices"),
    ("sustainability", "Sustainability Indices"),
]

# Stock indices
STOCK_INDICES = {
    "NSE": {
        "broad-market": [
            "^NSEI",
            "^NSMIDCP",
            "^CNX100",
            "^CNX200",
            "^CRSLDX",
            "^NSEMDCP50",
            "NIFTY_MIDCAP_100.NS",
            "^CNXSC",
            "^INDIAVIX",
            "NIFTYMIDCAP150.NS",
            "NIFTYSMLCAP50.NS",
            "NIFTYSMLCAP250.NS",
            "NIFTYMIDSML400.NS",
            "NIFTY500_MULTICAP.NS",
            "NIFTY_LARGEMID250.NS",
            "NIFTY_MID_SELECT.NS",
            "NIFTY_TOTAL_MKT.NS",
            "NIFTY_MICROCAP250.NS",
            "NIFTY500_LMS_EQL.NS",
        ],
        "sectoral": [
            "^NSEBANK",
            "^CNXAUTO",
            "NIFTY_FIN_SERVICE.NS",
            "^CNXFIN",
            "^CNXFMCG",
            "^CNXIT",
            "^CNXMEDIA",
            "^CNXMETAL",
            "^CNXPHARMA",
            "^CNXPSUBANK",
            "NIFTYPVTBANK.NS",
            "^CNXREALTY",
            "NIFTY_HEALTHCARE.NS",
            "NIFTY_CONSR_DURBL.NS",
            "NIFTY_OIL_AND_GAS.NS",
            "NIFTY_MIDSML_HLTH.NS",
            "NIFTY_FINSEREXBNK.NS",
        ],
        "strategy": [
            "^CNXDIVOP",
            "NI15.NS",
            "NIFTYQUALITY30.NS",
            "NV20.NS",
            "NIFTYTR2XLEV.NS",
            "NIFTYPR2XLEV.NS",
            "NIFTYTR1XINV.NS",
            "NIFTYPR1XINV.NS",
            "^NSEDIV",
            "NIFTYALPHA50.NS",
            "NIFTY100_EQL_WGT.NS",
            "NIFTY100LOWVOL30.NS",
            "NIFTY200QUALTY30.NS",
            "NIFTYALPHALOWVOL.NS",
            "NIFTY200MOMENTM30.NS",
            "NIFTY200_ALPHA_30.NS",
            "NIFTY500MOMENTM50.NS",
            "NIFTY_TOP_10_EW.NS",
            "NIFTY_HIGHBETA_50.NS",
            "NIFTY_TOP_15_EW.NS",
            "NIFTY100_ALPHA_30.NS",
            "NIFTY200_VALUE_30.NS",
            "NIFTY500_EW.NS",
            "NIFTY500_VALUE_50.NS",
            "NIFTY_TOP_20_EW.NS",
        ],
        "thematic": [
            "^CNXCMDT",
            "^CNXCONSUM",
            "NIFTY_CPSE.NS",
            "^CNXENERGY",
            "^CNXINFRA",
            "LIX15.NS",
            "^CNXMNC",
            "^CNXPSE",
            "^CNXSERVICE",
            "NIFTY100_ESG.NS",
            "NIFTY_IND_DIGITAL.NS",
            "NIFTY_INDIA_MFG.NS",
            "NIFTY_TATA_25_CAP.NS",
            "NIFTY_CAPITAL_MKT.NS",
            "NIFTY_MOBILITY.NS",
            "NIFTY100_ENH_ESG.NS",
            "NIFTY_COREHOUSING.NS",
            "NIFTY_HOUSING.NS",
            "NIFTY_IPO.NS",
            "NIFTY_RURAL.NS",
            "NIFTY_SHARIAH_25.NS",
            "NIFTY_TRANS_LOGIS.NS",
            "NIFTY50_SHARIAH.NS",
            "NIFTY500_SHARIAH.NS",
        ],
    },
    "BSE": {
        "broad-market": [
            "^BSESN",
            "FOCMID.BO",
            "SNSX50.BO",
            "SNXT50.BO",
            "BSE-100.BO",
            "BHRT22.BO",
            "SNSX60.BO",
            "BSE-MIDCAP.BO",
            "BSE-SMLCAP.BO",
            "BSE-200.BO",
            "MID150.BO",
            "SML250.BO",
            "LMI250.BO",
            "MSL400.BO",
            "BSE-500.BO",
            "LRGCAP.BO",
            "SMLSEL.BO",
            "MIDSEL.BO",
            "LCTMCI.BO",
            "SNXN30.BO",
        ],
        "sector": [
            "COMDTY.BO",
            "CONDIS.BO",
            "ENERGY.BO",
            "BSE-FMCG.BO",
            "FINSER.BO",
            "BSE-HC.BO",
            "INDSTR.BO",
            "BSE-IT.BO",
            "TELCOM.BO",
            "UTILS.BO",
            "BSE-AUTO.BO",
            "BSE-BANK.BO",
            "BSE-CG.BO",
            "BSE-CD.BO",
            "BSE-METAL.BO",
            "BSE-OILGAS.BO",
            "BSE-POWER.BO",
            "BSE-REALTY.BO",
            "BSE-TECK.BO",
        ],
        "thematic": [
            "DFRGRI.BO",
            "INFRASTRUCTURE.BO",
            "MFG.BO",
            "CPSE.BO",
            "BSE-PSU.BO",
        ],
        "strategy": [
            "BSEMOI.BO",
            "BSELVI.BO",
            "BSEQUI.BO",
            "BSEEVI.BO",
            "BSE-IPO.BO",
            "BSE-SMEIPO.BO",
        ],
        "sustainability": ["ESG100.BO"],
    },
}

# Periods
PERIODS = [
    ("1d", "1 Day"),
    ("5d", "5 Days"),
    ("1mo", "1 Month"),
    ("3mo", "3 Months"),
    ("6mo", "6 Months"),
    ("1y", "1 Year"),
    ("2y", "2 Years"),
    ("5y", "5 Years"),
    ("10y", "10 Years"),
    ("max", "Max"),
]
INTERVALS = {
    "1d": [
        ("1m", "1 Minute"),
        ("2m", "2 Minutes"),
        ("5m", "5 Minutes"),
        ("15m", "15 Minutes"),
        ("30m", "30 Minutes"),
        ("60m", "60 Minutes"),
        ("90m", "90 Minutes"),
    ],
    "5d": [
        ("1m", "1 Minute"),
        ("2m", "2 Minutes"),
        ("5m", "5 Minutes"),
        ("15m", "15 Minutes"),
        ("30m", "30 Minutes"),
        ("60m", "60 Minutes"),
        ("90m", "90 Minutes"),
    ],
    "1mo": [
        ("30m", "30 Minutes"),
        ("60m", "60 Minutes"),
        ("90m", "90 Minutes"),
        ("1d", "1 Day"),
    ],
    "3mo": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "6mo": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "1y": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "2y": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "5y": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "10y": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
    "max": [("1d", "1 Day"), ("5d", "5 Days"), ("1wk", "1 Week"), ("1mo", "1 Month")],
}

# Indicators
INDICATORS = [
    ("none", "None"),
    ("sma", "SMA 20"),
    ("ema", "EMA 20"),
    ("wma", "WMA 20"),
    ("dema", "DEMA 20"),
    ("tema", "TEMA 20"),
    ("trima", "TRIMA 20"),
    ("kama", "KAMA 10-2-30"),
    ("mama", "MAMA 10-0.5-0.05"),
    ("t3", "T3 10-0.7"),
    ("macd", "MACD 12-26-9"),
    ("stoch", "Stochastic 14-3"),
    ("stochf", "Stochastic Fast 14-3"),
    ("rsi", "RSI 14"),
    ("stochrsi", "Stochastic RSI 14-3"),
    ("willr", "Williams %R 14"),
    ("adxr", "ADXR 14"),
    ("apo", "APO 12-26"),
    ("ppo", "PPO 12-26-9"),
    ("mom", "Momentum 10"),
    ("bop", "Balance of Power"),
    ("cci", "CCI 20"),
    ("cmo", "Chande Momentum Oscillator 14"),
    ("roc", "Rate of Change 14"),
]
